# Generated by Django 5.0.6 on 2024-06-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rentcamera_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcamera',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
