# Generated by Django 5.0.6 on 2024-06-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_rentcamera_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcamera',
            name='photo',
            field=models.ImageField(upload_to='cameraStore'),
        ),
    ]
