# Generated by Django 5.0.6 on 2024-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbilling',
            name='customer_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='salesbilling',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesbilling',
            name='customer_phno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
