# Generated by Django 5.0.4 on 2024-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_salesbilling_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbilling',
            name='sales_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
