# Generated by Django 5.0.4 on 2024-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('specifications', models.TextField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='images/')),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_date', models.DateField()),
                ('type', models.CharField(choices=[('camera', 'Camera'), ('equipment', 'Equipment')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
