# Generated by Django 5.0.4 on 2024-05-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camera',
            new_name='SalesCamera',
        ),
    ]
